# Generated by Django 4.1.3 on 2022-11-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_employer_company_company_employer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default='None', max_length=3000, verbose_name='Kompaniya haqida'),
        ),
    ]
